version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    branches:
        only:
          - compilation
    steps:
      - checkout
      - run:
          name: git submodule
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: git config
          command: |
              git config --global user.name "jumperson"
              git config --global user.email "kazuya.fb@gmail.com"
      - run:
          name: merge to master
          command: |
            git checkout -b master origin/master
            git merge compilation

      - run:
          name: hugo
          command: |
              hugo version
              hugo

      - run:
          name: publish
          command: |
              git remote set-url origin git@github.com:jumperson/blog.git
              git add .
              git commit -m "[ci skip] publish"
              git push origin master